# Generated by Django 5.2.7 on 2025-12-25 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('about', 'О себе'), ('resume', 'Резюме'), ('projects', 'Проекты'), ('certificates', 'Сертификаты'), ('skills', 'Навыки'), ('custom', 'Пользовательский')], max_length=20, verbose_name='Тип раздела')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок раздела')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимый')),
            ],
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='slug'),
        ),
        migrations.AddIndex(
            model_name='sociallink',
            index=models.Index(fields=['url'], name='blog_social_url_421648_idx'),
        ),
        migrations.AddField(
            model_name='section',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blog.userprofile'),
        ),
    ]
